Solucion_Comercio/Controllers/TbBitacoraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Solucion_Comercio.Models;
using Solucion_Comercio.Servicios.Contrato;

namespace Solucion_Comercio.Controllers
{
    public class TbBitacoraController : Controller

    {

        private readonly BdcomercioContext _context;

        public TbBitacoraController(BdcomercioContext context)
        {
            _context = context;
        }

        // GET: TbBitacoraController
        public async Task<IActionResult> Index()
        {
            return _context.TbRoles != null ?
                          View(await _context.TbBitacoras.ToListAsync()) :
                          Problem("Entity set 'BdcomercioContext.TbBitacoras'  is null.");
        }

        // GET: TbBitacoraController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TbBitacoraController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TbBitacoraController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TbBitacoraController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TbBitacoraController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TbBitacoraController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TbBitacoraController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Solucion_Comercio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Comercio - @ViewData["Menu"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">


      <!-- Referencias para utilizar JQuery -->
    <link href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">

</head>
<body>
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
                <div class="sidebar-brand-icon">

                    <i class="fas fa-desktop"></i>

                </div>
                <div class="sidebar-brand-text mx-3">MI TIENDA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Productos -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBProductoes")"</a>
                <i class="nav-icon fas fa-table"></i>
                <span>Productos</span>
                </a>
            </li>

            <!-- Nav Item  Usuarios  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBUsuarios")"</a>
                <i class="nav-icon fas fa-users"></i>
                <span>Usuarios</span>
                </a>
            </li>
            <!-- Nav Item  Compras  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBCompras")"</a>
                <i class="fas fa-fw fa-tags fa-beat"></i>
                <span>Compras</span> 
                </a>
            </li>
            <!-- Nav Item  Facturas  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBFacturas")"</a>
                <i class="fas fa-fw fa-tags"></i>
                <span>Facturas</span>
                </a>
            </li>
            <!-- Nav Item  Inventario  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBInventarios")"</a>
                <i class="fas fa-fw fa-tags"></i>
                <span>Inventario</span>
                </a>
            </li>
            <!-- Nav Item  Pendientes  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBPendientes")"</a>
                <i class="nav-icon fas fa-table "></i>
                <span>Pendientes</span>
                </a>
            </li>
            <!-- Nav Item  Estados  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBEstadoes")"</a>
                <i class="fas fa-fw fa-cog"></i>
                <span>Estados</span>
                </a>
            </li>
            <!-- Nav Item  Roles  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TBRoles")"</a>
                <i class="fas fa-fw fa-cog"></i>
                <span>Roles</span>
                </a>
            </li>
            <!-- Nav Item  Roles  -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TbBitacora")"</a>
                <i class="fas fa-fw fa-cog"></i>
                <span>Bitacora</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("CerrarSeccion","Inicio")"</a>
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                <span>Cerrar Secion</span>
                </a>

            </li>


            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        
                        <div class="topbar-divider d-none d-sm-block"></div>

                     

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Daniel Ramirez Azofeiifa 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
      <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>